<!doctype html public "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-GB">
  <head>
    <title>$title$</title>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
    <meta name="description" content="Home of TopTools, a set of utilities to examine and measure screen elements at pixel level, helpful for web-designers and GUI-developers." />
    <meta name="keywords" content="screen loupe ruler base-converter color-picker screen-grabber snapshot clipboard utility" />
    <meta http-equiv="imagetoolbar" content="no" />
    <meta name="robots" content="index, follow, noarchive" />

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="screen.css" media="screen" />
  </head>
  <body>
  <div id="header">
    <h1>$title$</h1>
    <h3>$subtitle$</h3>
  </div>
  <div class="colmask leftmenu">
    <div class="colleft">
      <div class="col1">
        <!-- Column 1 start -->
        $content$
        <!-- Column 1 end -->
      </div>
      <div class="col2">
        <!-- Column 2 start -->
        $menuitems:menuitem()$
        <!-- Column 2 end -->
      </div>
    </div>
  </div>
  <div id="footer">
    <p class="left">Contact:
    <a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#105;&#110;&#102;&#111;&#64;&#116;&#111;&#112;&#116;&#111;&#111;&#108;&#115;&#46;&#111;&#114;&#103;">
          &#105;&#110;&#102;&#111;&#64;&#116;&#111;&#112;&#116;&#111;&#111;&#108;&#115;&#46;&#111;&#114;&#103;</a>
    </p>
    <p class="right">&copy; Willem Jongman 2011</p>
<!--     <p>&nbsp;</p>  -->
  </div>
  </body>
  </html>
