<!DOCTYPE html>
<html>
  <head>
    <title>$title$</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="A set of utilities to examine and measure screen elements at pixel level, helpful for web-designers and GUI-developers." />
    <meta name="keywords" content="screen-loupe screen-ruler base-converter color-picker screen-grabber snapshot clipboard utility" />
    <meta http-equiv="imagetoolbar" content="no" />
    <meta name="robots" content="index, follow, noarchive" />
    <meta name=viewport content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="style.css" media="screen" />
  </head>

<body><div id="wrap">

<div id="lastupdate">
  <p class="left">Latest version: $version$</p>
  <p class="right">Last page update: $lastupdate$</p>
</div>
<div id="header">
<!--   <p>Last update: $lastupdate$</p>  -->
  <h1>$title$</h1>
</div>


<div id="leftmenu">
<h2 class="hide">Menu:</h2>
<ul>
  $menuitems:menuitem()$
</ul>

<div style="text-align:center">
</div>

</div>

<div id="extras">
  <p><strong>Other utilities:</strong>
  <div class="selmenuitem">More to come..</div>
<!--     $menuitems:sidebaritem()$ -->
</div>

<div id="content">
  $content$
</div>

<div id="footer">
    <p class="left">Contact:
    <a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#105;&#110;&#102;&#111;&#64;&#116;&#111;&#112;&#116;&#111;&#111;&#108;&#115;&#46;&#111;&#114;&#103;">
          &#105;&#110;&#102;&#111;&#64;&#116;&#111;&#112;&#116;&#111;&#111;&#108;&#115;&#46;&#111;&#114;&#103;</a>
    </p>
    <p class="right">&copy; Willem Jongman 1998-$year$</p>
</div>

</div>

</body>
</html>
